/*
 * Copyright (c) 2023-2024. Compose Cupertino project and open source contributors.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

package icons

import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.items
import androidx.compose.foundation.pager.HorizontalPager
import androidx.compose.foundation.pager.rememberPagerState
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.unit.dp
import io.github.alexzhirkevich.cupertino.CupertinoAlertDialog
import io.github.alexzhirkevich.cupertino.CupertinoIcon
import io.github.alexzhirkevich.cupertino.CupertinoIconButton
import io.github.alexzhirkevich.cupertino.CupertinoNavigateBackButton
import io.github.alexzhirkevich.cupertino.CupertinoScaffold
import io.github.alexzhirkevich.cupertino.CupertinoSegmentedControl
import io.github.alexzhirkevich.cupertino.CupertinoSegmentedControlTab
import io.github.alexzhirkevich.cupertino.CupertinoText
import io.github.alexzhirkevich.cupertino.CupertinoTopAppBar
import io.github.alexzhirkevich.cupertino.ExperimentalCupertinoApi
import io.github.alexzhirkevich.cupertino.adaptive.AdaptiveWidget
import io.github.alexzhirkevich.cupertino.default
import io.github.alexzhirkevich.cupertino.icons.CupertinoIcons
import io.github.alexzhirkevich.cupertino.icons.filled.*
import io.github.alexzhirkevich.cupertino.icons.outlined.*

@OptIn(ExperimentalCupertinoApi::class)
@Composable
fun IconsScreen(
    component: IconsComponent
) {

    var isOutlined by remember {
        mutableStateOf(true)
    }

    val pagerState = rememberPagerState(
        pageCount = { 2 }
    )

    LaunchedEffect(isOutlined) {
        pagerState.animateScrollToPage(if (isOutlined) 0 else 1)
    }

    CupertinoScaffold(
        topBar = {
            CupertinoTopAppBar(
                navigationIcon = {

                    AdaptiveWidget(
                        cupertino = {
                            CupertinoNavigateBackButton(
                                onClick = component::onNavigateBack,
                            ) {
                                CupertinoText("Back")
                            }
                        },
                        material = {
                            IconButton(
                                onClick = component::onNavigateBack
                            ) {
                                Icon(
                                    imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                                    contentDescription = "Back"
                                )
                            }
                        }
                    )
                },
                title = {
                    CupertinoSegmentedControl(
                        modifier = Modifier
                            .width(200.dp),
                        selectedTabIndex = if (isOutlined) 0 else 1
                    ) {
                        CupertinoSegmentedControlTab(
                            isSelected = isOutlined,
                            onClick = {
                                isOutlined = true
                            }
                        ) {
                            CupertinoText("Outlined")
                        }
                        CupertinoSegmentedControlTab(
                            isSelected = !isOutlined,
                            onClick = {
                                isOutlined = false

                            }
                        ) {
                            CupertinoText("Filled")
                        }
                    }
                }
            )
        }
    ) { pv ->

        var selectedIcon by remember {
            mutableStateOf<ImageVector?>(null)
        }
        if (selectedIcon != null) {
            CupertinoAlertDialog(
                title = {
                    CupertinoIcon(
                        imageVector = selectedIcon!!,
                        contentDescription = null
                    )
                },
                message = {
                    CupertinoText(
                        selectedIcon!!.name
                    )
                },
                onDismissRequest = {
                    selectedIcon = null
                }
            ) {
                default(onClick = {
                    selectedIcon = null
                }) {
                    CupertinoText("Close")
                }
            }
        }

        HorizontalPager(
            state = pagerState,
            userScrollEnabled = false
        ) { page ->
            LazyVerticalGrid(
                modifier = Modifier.fillMaxSize(),
                columns = GridCells.Adaptive(48.dp),
                contentPadding = pv
            ) {
                items(if (page == 0) Outlined else Filled) {
                    CupertinoIconButton(
                        onClick = {
                            selectedIcon = it
                        }
                    ) {
                        CupertinoIcon(
                            imageVector = it,
                            contentDescription = it.name
                        )
                    }
                }
            }
        }
    }
}

private val Outlined = listOf(
    CupertinoIcons.Outlined.Airplane,
    CupertinoIcons.Outlined.AirplaneArrival,
    CupertinoIcons.Outlined.AirplaneDeparture,
    CupertinoIcons.Outlined.Airplayaudio,
    CupertinoIcons.Outlined.Airpods,
    CupertinoIcons.Outlined.AirpodsGen3,
    CupertinoIcons.Outlined.Airpodsmax,
    CupertinoIcons.Outlined.Airpodspro,
    CupertinoIcons.Outlined.Airtag,
    CupertinoIcons.Outlined.Alarm,
    CupertinoIcons.Outlined.Alt,
    CupertinoIcons.Outlined.Angle,
    CupertinoIcons.Outlined.AntennaRadiowavesLeftAndRight,
    CupertinoIcons.Outlined.AntennaRadiowavesLeftAndRightSlash,
    CupertinoIcons.Outlined.AppleLogo,
    CupertinoIcons.Outlined.Applepencil,
    CupertinoIcons.Outlined.Appletv,
    CupertinoIcons.Outlined.Applewatch,
    CupertinoIcons.Outlined.ApplewatchRadiowavesLeftAndRight,
    CupertinoIcons.Outlined.ApplewatchWatchface,
    CupertinoIcons.Outlined.Archivebox,
    CupertinoIcons.Outlined.Arrow3Trianglepath,
    CupertinoIcons.Outlined.ArrowClockwise,
    CupertinoIcons.Outlined.ArrowCounterclockwise,
    CupertinoIcons.Outlined.ArrowCounterclockwiseIcloud,
    CupertinoIcons.Outlined.ArrowDown,
    CupertinoIcons.Outlined.ArrowDownAndLineHorizontalAndArrowUp,
    CupertinoIcons.Outlined.ArrowDownCircle,
    CupertinoIcons.Outlined.ArrowDownDoc,
    CupertinoIcons.Outlined.ArrowDownRightAndArrowUpLeft,
    CupertinoIcons.Outlined.ArrowDownToLine,
    CupertinoIcons.Outlined.ArrowLeftAndRight,
    CupertinoIcons.Outlined.ArrowLeftArrowRight,
    CupertinoIcons.Outlined.ArrowTriangle2Circlepath,
    CupertinoIcons.Outlined.ArrowTriangle2CirclepathCamera,
    CupertinoIcons.Outlined.ArrowTriangleBranch,
    CupertinoIcons.Outlined.ArrowTurnDownLeft,
    CupertinoIcons.Outlined.ArrowTurnDownRight,
    CupertinoIcons.Outlined.ArrowTurnRightUp,
    CupertinoIcons.Outlined.ArrowTurnUpForwardIphone,
    CupertinoIcons.Outlined.ArrowTurnUpLeft,
    CupertinoIcons.Outlined.ArrowTurnUpRight,
    CupertinoIcons.Outlined.ArrowUpAndDown,
    CupertinoIcons.Outlined.ArrowUpArrowDown,
    CupertinoIcons.Outlined.ArrowUpDoc,
    CupertinoIcons.Outlined.ArrowUpLeftAndArrowDownRight,
    CupertinoIcons.Outlined.ArrowUturnLeft,
    CupertinoIcons.Outlined.ArrowUturnRight,
    CupertinoIcons.Outlined.ArrowshapeTurnUpLeft,
    CupertinoIcons.Outlined.ArrowshapeTurnUpLeft2,
    CupertinoIcons.Outlined.At,
    CupertinoIcons.Outlined.Backward,
    CupertinoIcons.Outlined.BackwardEnd,
    CupertinoIcons.Outlined.Bag,
    CupertinoIcons.Outlined.BagBadgeMinus,
    CupertinoIcons.Outlined.BagBadgePlus,
    CupertinoIcons.Outlined.Balloon,
    CupertinoIcons.Outlined.Bandage,
    CupertinoIcons.Outlined.Banknote,
    CupertinoIcons.Outlined.Barcode,
    CupertinoIcons.Outlined.BarcodeViewfinder,
    CupertinoIcons.Outlined.Baseball,
    CupertinoIcons.Outlined.Basket,
    CupertinoIcons.Outlined.Basketball,
    CupertinoIcons.Outlined.Battery100,
    CupertinoIcons.Outlined.BedDouble,
    CupertinoIcons.Outlined.Bell,
    CupertinoIcons.Outlined.BellAndWavesLeftAndRight,
    CupertinoIcons.Outlined.BellBadge,
    CupertinoIcons.Outlined.BellCircle,
    CupertinoIcons.Outlined.BellSlash,
    CupertinoIcons.Outlined.Bicycle,
    CupertinoIcons.Outlined.Binoculars,
    CupertinoIcons.Outlined.BirthdayCake,
    CupertinoIcons.Outlined.Bitcoinsign,
    CupertinoIcons.Outlined.Bolt,
    CupertinoIcons.Outlined.BoltHorizontal,
    CupertinoIcons.Outlined.BoltSlash,
    CupertinoIcons.Outlined.Book,
    CupertinoIcons.Outlined.BookCircle,
    CupertinoIcons.Outlined.BookClosed,
    CupertinoIcons.Outlined.Bookmark,
    CupertinoIcons.Outlined.BookmarkSlash,
    CupertinoIcons.Outlined.Brain,
    CupertinoIcons.Outlined.BrainHeadProfile,
    CupertinoIcons.Outlined.Briefcase,
    CupertinoIcons.Outlined.BubbleLeft,
    CupertinoIcons.Outlined.BubbleRight,
    CupertinoIcons.Outlined.Building,
    CupertinoIcons.Outlined.Building2,
    CupertinoIcons.Outlined.Burn,
    CupertinoIcons.Outlined.Burst,
    CupertinoIcons.Outlined.CableConnector,
    CupertinoIcons.Outlined.CableConnectorHorizontal,
    CupertinoIcons.Outlined.Calendar,
    CupertinoIcons.Outlined.CalendarBadgePlus,
    CupertinoIcons.Outlined.Camera,
    CupertinoIcons.Outlined.CameraCircle,
    CupertinoIcons.Outlined.CameraFilters,
    CupertinoIcons.Outlined.CameraViewfinder,
    CupertinoIcons.Outlined.Candybarphone,
    CupertinoIcons.Outlined.Capslock,
    CupertinoIcons.Outlined.Car,
    CupertinoIcons.Outlined.Cart,
    CupertinoIcons.Outlined.CartBadgeMinus,
    CupertinoIcons.Outlined.CartBadgePlus,
    CupertinoIcons.Outlined.Case,
    CupertinoIcons.Outlined.Centsign,
    CupertinoIcons.Outlined.Character,
    CupertinoIcons.Outlined.ChartBar,
    CupertinoIcons.Outlined.ChartLineDowntrendXyaxis,
    CupertinoIcons.Outlined.ChartLineUptrendXyaxis,
    CupertinoIcons.Outlined.CheckerboardShield,
    CupertinoIcons.Outlined.Checklist,
    CupertinoIcons.Outlined.ChecklistChecked,
    CupertinoIcons.Outlined.ChecklistUnchecked,
    CupertinoIcons.Outlined.Checkmark,
    CupertinoIcons.Outlined.CheckmarkCircle,
    CupertinoIcons.Outlined.CheckmarkIcloud,
    CupertinoIcons.Outlined.CheckmarkMessage,
    CupertinoIcons.Outlined.CheckmarkSeal,
    CupertinoIcons.Outlined.CheckmarkShield,
    CupertinoIcons.Outlined.CheckmarkSquare,
    CupertinoIcons.Outlined.ChevronBackward,
    CupertinoIcons.Outlined.ChevronDown,
    CupertinoIcons.Outlined.ChevronForward,
    CupertinoIcons.Outlined.ChevronLeftForwardslashChevronRight,
    CupertinoIcons.Outlined.ChevronUp,
    CupertinoIcons.Outlined.Clear,
    CupertinoIcons.Outlined.Clipboard,
    CupertinoIcons.Outlined.Clock,
    CupertinoIcons.Outlined.ClockArrowCirclepath,
    CupertinoIcons.Outlined.Cloud,
    CupertinoIcons.Outlined.Command,
    CupertinoIcons.Outlined.CompassDrawing,
    CupertinoIcons.Outlined.Cone,
    CupertinoIcons.Outlined.Cpu,
    CupertinoIcons.Outlined.Creditcard,
    CupertinoIcons.Outlined.CreditcardTrianglebadgeExclamationmark,
    CupertinoIcons.Outlined.Crop,
    CupertinoIcons.Outlined.CropRotate,
    CupertinoIcons.Outlined.Cross,
    CupertinoIcons.Outlined.CrossCircle,
    CupertinoIcons.Outlined.CrossVial,
    CupertinoIcons.Outlined.Crown,
    CupertinoIcons.Outlined.Cube,
    CupertinoIcons.Outlined.CupAndSaucer,
    CupertinoIcons.Outlined.Curlybraces,
    CupertinoIcons.Outlined.CursorarrowRays,
    CupertinoIcons.Outlined.DeleteLeft,
    CupertinoIcons.Outlined.DeleteRight,
    CupertinoIcons.Outlined.Desktopcomputer,
    CupertinoIcons.Outlined.Dice,
    CupertinoIcons.Outlined.Display,
    CupertinoIcons.Outlined.Divide,
    CupertinoIcons.Outlined.Doc,
    CupertinoIcons.Outlined.DocBadgeArrowUp,
    CupertinoIcons.Outlined.DocBadgePlus,
    CupertinoIcons.Outlined.DocOnDoc,
    CupertinoIcons.Outlined.DocPlaintext,
    CupertinoIcons.Outlined.DocText,
    CupertinoIcons.Outlined.DocTextMagnifyingglass,
    CupertinoIcons.Outlined.Dollarsign,
    CupertinoIcons.Outlined.DollarsignArrowCirclepath,
    CupertinoIcons.Outlined.DoorLeftHandClosed,
    CupertinoIcons.Outlined.DoorLeftHandOpen,
    CupertinoIcons.Outlined.DotRadiowavesLeftAndRight,
    CupertinoIcons.Outlined.DotRadiowavesUpForward,
    CupertinoIcons.Outlined.Drop,
    CupertinoIcons.Outlined.Ear,
    CupertinoIcons.Outlined.Earpods,
    CupertinoIcons.Outlined.Ellipsis,
    CupertinoIcons.Outlined.EllipsisBubble,
    CupertinoIcons.Outlined.EllipsisCircle,
    CupertinoIcons.Outlined.EllipsisCurlybraces,
    CupertinoIcons.Outlined.EllipsisMessage,
    CupertinoIcons.Outlined.Envelope,
    CupertinoIcons.Outlined.EnvelopeBadge,
    CupertinoIcons.Outlined.EnvelopeCircle,
    CupertinoIcons.Outlined.EnvelopeOpen,
    CupertinoIcons.Outlined.Eraser,
    CupertinoIcons.Outlined.Eurosign,
    CupertinoIcons.Outlined.Exclamationmark,
    CupertinoIcons.Outlined.Exclamationmark2,
    CupertinoIcons.Outlined.Exclamationmark3,
    CupertinoIcons.Outlined.ExclamationmarkArrowTriangle2Circlepath,
    CupertinoIcons.Outlined.ExclamationmarkCircle,
    CupertinoIcons.Outlined.ExclamationmarkIcloud,
    CupertinoIcons.Outlined.ExclamationmarkSquare,
    CupertinoIcons.Outlined.ExclamationmarkTriangle,
    CupertinoIcons.Outlined.Externaldrive,
    CupertinoIcons.Outlined.Eye,
    CupertinoIcons.Outlined.EyeSlash,
    CupertinoIcons.Outlined.Eyebrow,
    CupertinoIcons.Outlined.Eyedropper,
    CupertinoIcons.Outlined.Eyeglasses,
    CupertinoIcons.Outlined.Eyes,
    CupertinoIcons.Outlined.FaceSmiling,
    CupertinoIcons.Outlined.FaceSmilingInverse,
    CupertinoIcons.Outlined.Faceid,
    CupertinoIcons.Outlined.Facemask,
    CupertinoIcons.Outlined.Fanblades,
    CupertinoIcons.Outlined.FanbladesSlash,
    CupertinoIcons.Outlined.Fibrechannel,
    CupertinoIcons.Outlined.FigureStand,
    CupertinoIcons.Outlined.FigureWalk,
    CupertinoIcons.Outlined.Film,
    CupertinoIcons.Outlined.Flag,
    CupertinoIcons.Outlined.Flag2Crossed,
    CupertinoIcons.Outlined.FlagCheckered2Crossed,
    CupertinoIcons.Outlined.FlagSlash,
    CupertinoIcons.Outlined.Flame,
    CupertinoIcons.Outlined.Flowchart,
    CupertinoIcons.Outlined.Folder,
    CupertinoIcons.Outlined.FolderBadgePlus,
    CupertinoIcons.Outlined.Football,
    CupertinoIcons.Outlined.ForkKnife,
    CupertinoIcons.Outlined.ForkKnifeCircle,
    CupertinoIcons.Outlined.Forward,
    CupertinoIcons.Outlined.ForwardEnd,
    CupertinoIcons.Outlined.Francsign,
    CupertinoIcons.Outlined.Fuelpump,
    CupertinoIcons.Outlined.Gamecontroller,
    CupertinoIcons.Outlined.Gear,
    CupertinoIcons.Outlined.Gearshape,
    CupertinoIcons.Outlined.Gearshape2,
    CupertinoIcons.Outlined.Gift,
    CupertinoIcons.Outlined.Giftcard,
    CupertinoIcons.Outlined.GlobeDesk,
    CupertinoIcons.Outlined.Gobackward,
    CupertinoIcons.Outlined.Goforward,
    CupertinoIcons.Outlined.Graduationcap,
    CupertinoIcons.Outlined.Grid,
    CupertinoIcons.Outlined.Hammer,
    CupertinoIcons.Outlined.HandDraw,
    CupertinoIcons.Outlined.HandPointUp,
    CupertinoIcons.Outlined.HandPointUpLeft,
    CupertinoIcons.Outlined.HandRaised,
    CupertinoIcons.Outlined.HandRaisedSlash,
    CupertinoIcons.Outlined.HandTap,
    CupertinoIcons.Outlined.HandThumbsdown,
    CupertinoIcons.Outlined.HandThumbsup,
    CupertinoIcons.Outlined.HandWave,
    CupertinoIcons.Outlined.HandsSparkles,
    CupertinoIcons.Outlined.Headphones,
    CupertinoIcons.Outlined.HeadphonesCircle,
    CupertinoIcons.Outlined.Heart,
    CupertinoIcons.Outlined.HeartCircle,
    CupertinoIcons.Outlined.HeartSlash,
    CupertinoIcons.Outlined.HeartTextSquare,
    CupertinoIcons.Outlined.Hifispeaker,
    CupertinoIcons.Outlined.Highlighter,
    CupertinoIcons.Outlined.Homekit,
    CupertinoIcons.Outlined.Homepod,
    CupertinoIcons.Outlined.Homepodmini,
    CupertinoIcons.Outlined.Hourglass,
    CupertinoIcons.Outlined.House,
    CupertinoIcons.Outlined.Hryvniasign,
    CupertinoIcons.Outlined.Icloud,
    CupertinoIcons.Outlined.IcloudAndArrowDown,
    CupertinoIcons.Outlined.IcloudAndArrowUp,
    CupertinoIcons.Outlined.Infinity,
    CupertinoIcons.Outlined.Info,
    CupertinoIcons.Outlined.InfoBubble,
    CupertinoIcons.Outlined.InfoCircle,
    CupertinoIcons.Outlined.InfoSquare,
    CupertinoIcons.Outlined.Ipad,
    CupertinoIcons.Outlined.IpadAndIphone,
    CupertinoIcons.Outlined.IpadHomebutton,
    CupertinoIcons.Outlined.Iphone,
    CupertinoIcons.Outlined.IphoneBadgePlay,
    CupertinoIcons.Outlined.IphoneHomebutton,
    CupertinoIcons.Outlined.IphoneHomebuttonRadiowavesLeftAndRight,
    CupertinoIcons.Outlined.IphoneRadiowavesLeftAndRight,
    CupertinoIcons.Outlined.Key,
    CupertinoIcons.Outlined.KeyIcloud,
    CupertinoIcons.Outlined.Keyboard,
    CupertinoIcons.Outlined.Lanyardcard,
    CupertinoIcons.Outlined.Laptopcomputer,
    CupertinoIcons.Outlined.LaptopcomputerAndIpad,
    CupertinoIcons.Outlined.LaptopcomputerAndIphone,
    CupertinoIcons.Outlined.Leaf,
    CupertinoIcons.Outlined.Level,
    CupertinoIcons.Outlined.Lifepreserver,
    CupertinoIcons.Outlined.LightBeaconMax,
    CupertinoIcons.Outlined.LightMax,
    CupertinoIcons.Outlined.LightMin,
    CupertinoIcons.Outlined.Lightbulb,
    CupertinoIcons.Outlined.LightbulbSlash,
    CupertinoIcons.Outlined.Link,
    CupertinoIcons.Outlined.LinkBadgePlus,
    CupertinoIcons.Outlined.LinkCircle,
    CupertinoIcons.Outlined.Lirasign,
    CupertinoIcons.Outlined.ListBullet,
    CupertinoIcons.Outlined.ListBulletCircle,
    CupertinoIcons.Outlined.ListBulletClipboard,
    CupertinoIcons.Outlined.ListBulletIndent,
    CupertinoIcons.Outlined.ListClipboard,
    CupertinoIcons.Outlined.ListNumber,
    CupertinoIcons.Outlined.Livephoto,
    CupertinoIcons.Outlined.Location,
    CupertinoIcons.Outlined.Lock,
    CupertinoIcons.Outlined.LockCircle,
    CupertinoIcons.Outlined.LockOpen,
    CupertinoIcons.Outlined.LockSlash,
    CupertinoIcons.Outlined.Macwindow,
    CupertinoIcons.Outlined.MacwindowBadgePlus,
    CupertinoIcons.Outlined.Magazine,
    CupertinoIcons.Outlined.Mail,
    CupertinoIcons.Outlined.MailStack,
    CupertinoIcons.Outlined.Map,
    CupertinoIcons.Outlined.Mappin,
    CupertinoIcons.Outlined.MappinAndEllipse,
    CupertinoIcons.Outlined.MappinSlash,
    CupertinoIcons.Outlined.Medal,
    CupertinoIcons.Outlined.Megaphone,
    CupertinoIcons.Outlined.Memories,
    CupertinoIcons.Outlined.MenubarRectangle,
    CupertinoIcons.Outlined.Menucard,
    CupertinoIcons.Outlined.Message,
    CupertinoIcons.Outlined.MessageBadge,
    CupertinoIcons.Outlined.Mic,
    CupertinoIcons.Outlined.MicSlash,
    CupertinoIcons.Outlined.Minus,
    CupertinoIcons.Outlined.MinusCircle,
    CupertinoIcons.Outlined.MinusMagnifyingglass,
    CupertinoIcons.Outlined.Moon,
    CupertinoIcons.Outlined.MoonStars,
    CupertinoIcons.Outlined.Mount,
    CupertinoIcons.Outlined.Multiply,
    CupertinoIcons.Outlined.MusicMic,
    CupertinoIcons.Outlined.MusicNote,
    CupertinoIcons.Outlined.MusicNoteList,
    CupertinoIcons.Outlined.MusicQuarternote3,
    CupertinoIcons.Outlined.Network,
    CupertinoIcons.Outlined.Newspaper,
    CupertinoIcons.Outlined.Nosign,
    CupertinoIcons.Outlined.NoteText,
    CupertinoIcons.Outlined.NoteTextBadgePlus,
    CupertinoIcons.Outlined.Number,
    CupertinoIcons.Outlined.Opticaldisc,
    CupertinoIcons.Outlined.Option,
    CupertinoIcons.Outlined.Paintbrush,
    CupertinoIcons.Outlined.PaintbrushPointed,
    CupertinoIcons.Outlined.Paintpalette,
    CupertinoIcons.Outlined.Paperclip,
    CupertinoIcons.Outlined.PaperclipBadgeEllipsis,
    CupertinoIcons.Outlined.PaperclipCircle,
    CupertinoIcons.Outlined.Paperplane,
    CupertinoIcons.Outlined.Paragraphsign,
    CupertinoIcons.Outlined.PartyPopper,
    CupertinoIcons.Outlined.Pause,
    CupertinoIcons.Outlined.PauseCircle,
    CupertinoIcons.Outlined.Pawprint,
    CupertinoIcons.Outlined.Pencil,
    CupertinoIcons.Outlined.PencilCircle,
    CupertinoIcons.Outlined.PencilTipCropCircle,
    CupertinoIcons.Outlined.Percent,
    CupertinoIcons.Outlined.Person,
    CupertinoIcons.Outlined.Person2,
    CupertinoIcons.Outlined.PersonAndBackgroundDotted,
    CupertinoIcons.Outlined.PersonCircle,
    CupertinoIcons.Outlined.PersonCropCircle,
    CupertinoIcons.Outlined.PersonCropCircleBadgeMinus,
    CupertinoIcons.Outlined.PersonCropCircleBadgePlus,
    CupertinoIcons.Outlined.PersonCropSquare,
    CupertinoIcons.Outlined.PersonIcloud,
    CupertinoIcons.Outlined.PersonTextRectangle,
    CupertinoIcons.Outlined.PersonWave2,
    CupertinoIcons.Outlined.Personalhotspot,
    CupertinoIcons.Outlined.Phone,
    CupertinoIcons.Outlined.PhoneAndWaveform,
    CupertinoIcons.Outlined.PhoneArrowDownLeft,
    CupertinoIcons.Outlined.PhoneArrowUpRight,
    CupertinoIcons.Outlined.PhoneBadgePlus,
    CupertinoIcons.Outlined.PhoneCircle,
    CupertinoIcons.Outlined.PhoneConnection,
    CupertinoIcons.Outlined.Photo,
    CupertinoIcons.Outlined.PhotoStack,
    CupertinoIcons.Outlined.PhotoTv,
    CupertinoIcons.Outlined.Pill,
    CupertinoIcons.Outlined.Pin,
    CupertinoIcons.Outlined.PinCircle,
    CupertinoIcons.Outlined.PinSlash,
    CupertinoIcons.Outlined.Pip,
    CupertinoIcons.Outlined.PipEnter,
    CupertinoIcons.Outlined.PipExit,
    CupertinoIcons.Outlined.Play,
    CupertinoIcons.Outlined.PlayCircle,
    CupertinoIcons.Outlined.PlayDisplay,
    CupertinoIcons.Outlined.Plus,
    CupertinoIcons.Outlined.PlusApp,
    CupertinoIcons.Outlined.PlusBubble,
    CupertinoIcons.Outlined.PlusCircle,
    CupertinoIcons.Outlined.PlusMagnifyingglass,
    CupertinoIcons.Outlined.PlusMessage,
    CupertinoIcons.Outlined.PlusSquare,
    CupertinoIcons.Outlined.PlusViewfinder,
    CupertinoIcons.Outlined.Popcorn,
    CupertinoIcons.Outlined.Power,
    CupertinoIcons.Outlined.PowerCircle,
    CupertinoIcons.Outlined.Printer,
    CupertinoIcons.Outlined.Puzzlepiece,
    CupertinoIcons.Outlined.PuzzlepieceExtension,
    CupertinoIcons.Outlined.Qrcode,
    CupertinoIcons.Outlined.QrcodeViewfinder,
    CupertinoIcons.Outlined.Questionmark,
    CupertinoIcons.Outlined.QuestionmarkApp,
    CupertinoIcons.Outlined.QuestionmarkCircle,
    CupertinoIcons.Outlined.QuestionmarkFolder,
    CupertinoIcons.Outlined.QuestionmarkSquare,
    CupertinoIcons.Outlined.QuoteClosing,
    CupertinoIcons.Outlined.QuoteOpening,
    CupertinoIcons.Outlined.Rays,
    CupertinoIcons.Outlined.RecordCircle,
    CupertinoIcons.Outlined.Recordingtape,
    CupertinoIcons.Outlined.RectangleArrowtriangle2Outward,
    CupertinoIcons.Outlined.RectangleConnectedToLineBelow,
    CupertinoIcons.Outlined.RectanglePortraitAndArrowForward,
    CupertinoIcons.Outlined.RectanglePortraitArrowtriangle2Outward,
    CupertinoIcons.Outlined.RectangleStack,
    CupertinoIcons.Outlined.Repeat,
    CupertinoIcons.Outlined.Rosette,
    CupertinoIcons.Outlined.Rotate3d,
    CupertinoIcons.Outlined.RotateLeft,
    CupertinoIcons.Outlined.RotateRight,
    CupertinoIcons.Outlined.Rublesign,
    CupertinoIcons.Outlined.Ruler,
    CupertinoIcons.Outlined.Safari,
    CupertinoIcons.Outlined.Scalemass,
    CupertinoIcons.Outlined.Scissors,
    CupertinoIcons.Outlined.Scope,
    CupertinoIcons.Outlined.Scribble,
    CupertinoIcons.Outlined.ScribbleVariable,
    CupertinoIcons.Outlined.Scroll,
    CupertinoIcons.Outlined.ServerRack,
    CupertinoIcons.Outlined.Shareplay,
    CupertinoIcons.Outlined.ShareplaySlash,
    CupertinoIcons.Outlined.ShazamLogo,
    CupertinoIcons.Outlined.Shield,
    CupertinoIcons.Outlined.ShieldSlash,
    CupertinoIcons.Outlined.Shippingbox,
    CupertinoIcons.Outlined.Shuffle,
    CupertinoIcons.Outlined.SidebarLeft,
    CupertinoIcons.Outlined.SidebarRight,
    CupertinoIcons.Outlined.Simcard,
    CupertinoIcons.Outlined.Skew,
    CupertinoIcons.Outlined.SliderHorizontal3,
    CupertinoIcons.Outlined.SliderVertical3,
    CupertinoIcons.Outlined.Snowflake,
    CupertinoIcons.Outlined.Soccerball,
    CupertinoIcons.Outlined.Space,
    CupertinoIcons.Outlined.Sparkle,
    CupertinoIcons.Outlined.Sparkles,
    CupertinoIcons.Outlined.Speaker,
    CupertinoIcons.Outlined.SpeakerMinus,
    CupertinoIcons.Outlined.SpeakerPlus,
    CupertinoIcons.Outlined.SpeakerSlash,
    CupertinoIcons.Outlined.SpeakerWave2,
    CupertinoIcons.Outlined.Speedometer,
    CupertinoIcons.Outlined.Square3Layers3dDownLeft,
    CupertinoIcons.Outlined.Square3Layers3dDownRight,
    CupertinoIcons.Outlined.SquareAndArrowUp,
    CupertinoIcons.Outlined.SquareAndPencil,
    CupertinoIcons.Outlined.SquareOnSquare,
    CupertinoIcons.Outlined.SquareSplit1x2,
    CupertinoIcons.Outlined.SquareSplit2x1,
    CupertinoIcons.Outlined.SquareStack,
    CupertinoIcons.Outlined.SquareStack3dUp,
    CupertinoIcons.Outlined.Star,
    CupertinoIcons.Outlined.StarSlash,
    CupertinoIcons.Outlined.Staroflife,
    CupertinoIcons.Outlined.Sterlingsign,
    CupertinoIcons.Outlined.Stethoscope,
    CupertinoIcons.Outlined.Stop,
    CupertinoIcons.Outlined.StopCircle,
    CupertinoIcons.Outlined.Suitcase,
    CupertinoIcons.Outlined.Sum,
    CupertinoIcons.Outlined.SunMax,
    CupertinoIcons.Outlined.Swift,
    CupertinoIcons.Outlined.Tag,
    CupertinoIcons.Outlined.Target,
    CupertinoIcons.Outlined.TennisRacket,
    CupertinoIcons.Outlined.Terminal,
    CupertinoIcons.Outlined.TextBubble,
    CupertinoIcons.Outlined.TextMagnifyingglass,
    CupertinoIcons.Outlined.Theatermasks,
    CupertinoIcons.Outlined.Timer,
    CupertinoIcons.Outlined.Touchid,
    CupertinoIcons.Outlined.Trash,
    CupertinoIcons.Outlined.TrashSlash,
    CupertinoIcons.Outlined.TrayAndArrowDown,
    CupertinoIcons.Outlined.TrayAndArrowUp,
    CupertinoIcons.Outlined.Trophy,
    CupertinoIcons.Outlined.Tshirt,
    CupertinoIcons.Outlined.Tv,
    CupertinoIcons.Outlined.Umbrella,
    CupertinoIcons.Outlined.Video,
    CupertinoIcons.Outlined.VideoCircle,
    CupertinoIcons.Outlined.VideoSlash,
    CupertinoIcons.Outlined.Volleyball,
    CupertinoIcons.Outlined.WalletPass,
    CupertinoIcons.Outlined.WandAndStars,
    CupertinoIcons.Outlined.WandAndStarsInverse,
    CupertinoIcons.Outlined.Waveform,
    CupertinoIcons.Outlined.WaveformAndMagnifyingglass,
    CupertinoIcons.Outlined.WaveformAndMic,
    CupertinoIcons.Outlined.WaveformPathEcg,
    CupertinoIcons.Outlined.WebCamera,
    CupertinoIcons.Outlined.Wifi,
    CupertinoIcons.Outlined.WifiExclamationmark,
    CupertinoIcons.Outlined.WifiRouter,
    CupertinoIcons.Outlined.WifiSlash,
    CupertinoIcons.Outlined.Wind,
    CupertinoIcons.Outlined.Wineglass,
    CupertinoIcons.Outlined.WrenchAndScrewdriver,
    CupertinoIcons.Outlined.Xmark,
    CupertinoIcons.Outlined.XmarkApp,
    CupertinoIcons.Outlined.XmarkBin,
    CupertinoIcons.Outlined.XmarkCircle,
    CupertinoIcons.Outlined.XmarkIcloud,
    CupertinoIcons.Outlined.XmarkSeal,
    CupertinoIcons.Outlined.XmarkShield,
    CupertinoIcons.Outlined.Yensign,
    CupertinoIcons.Outlined.Zzz,
    CupertinoIcons.Outlined._4kTv,
)

private val Filled = listOf(
    CupertinoIcons.Filled.Airtag,
    CupertinoIcons.Filled.Alarm,
    CupertinoIcons.Filled.Appletv,
    CupertinoIcons.Filled.Archivebox,
    CupertinoIcons.Filled.ArrowClockwiseCircle,
    CupertinoIcons.Filled.ArrowCounterclockwiseCircle,
    CupertinoIcons.Filled.ArrowCounterclockwiseIcloud,
    CupertinoIcons.Filled.ArrowDownCircle,
    CupertinoIcons.Filled.ArrowDownDoc,
    CupertinoIcons.Filled.ArrowTriangle2CirclepathCamera,
    CupertinoIcons.Filled.ArrowTriangle2CirclepathCircle,
    CupertinoIcons.Filled.ArrowTurnUpForwardIphone,
    CupertinoIcons.Filled.ArrowUpDoc,
    CupertinoIcons.Filled.ArrowshapeTurnUpLeft,
    CupertinoIcons.Filled.ArrowshapeTurnUpLeft2,
    CupertinoIcons.Filled.Backward,
    CupertinoIcons.Filled.BackwardEnd,
    CupertinoIcons.Filled.Bag,
    CupertinoIcons.Filled.BagBadgeMinus,
    CupertinoIcons.Filled.BagBadgePlus,
    CupertinoIcons.Filled.Balloon,
    CupertinoIcons.Filled.Bandage,
    CupertinoIcons.Filled.Banknote,
    CupertinoIcons.Filled.Baseball,
    CupertinoIcons.Filled.Basket,
    CupertinoIcons.Filled.Basketball,
    CupertinoIcons.Filled.BedDouble,
    CupertinoIcons.Filled.Bell,
    CupertinoIcons.Filled.BellAndWavesLeftAndRight,
    CupertinoIcons.Filled.BellBadge,
    CupertinoIcons.Filled.BellCircle,
    CupertinoIcons.Filled.BellSlash,
    CupertinoIcons.Filled.Binoculars,
    CupertinoIcons.Filled.BirthdayCake,
    CupertinoIcons.Filled.Bolt,
    CupertinoIcons.Filled.BoltHorizontal,
    CupertinoIcons.Filled.BoltSlash,
    CupertinoIcons.Filled.Book,
    CupertinoIcons.Filled.BookCircle,
    CupertinoIcons.Filled.BookClosed,
    CupertinoIcons.Filled.Bookmark,
    CupertinoIcons.Filled.BookmarkSlash,
    CupertinoIcons.Filled.Briefcase,
    CupertinoIcons.Filled.BubbleLeft,
    CupertinoIcons.Filled.BubbleRight,
    CupertinoIcons.Filled.Building,
    CupertinoIcons.Filled.Building2,
    CupertinoIcons.Filled.Burst,
    CupertinoIcons.Filled.Camera,
    CupertinoIcons.Filled.CameraCircle,
    CupertinoIcons.Filled.Capslock,
    CupertinoIcons.Filled.Car,
    CupertinoIcons.Filled.Cart,
    CupertinoIcons.Filled.CartBadgeMinus,
    CupertinoIcons.Filled.CartBadgePlus,
    CupertinoIcons.Filled.Case,
    CupertinoIcons.Filled.ChartBar,
    CupertinoIcons.Filled.CheckmarkCircle,
    CupertinoIcons.Filled.CheckmarkIcloud,
    CupertinoIcons.Filled.CheckmarkMessage,
    CupertinoIcons.Filled.CheckmarkSeal,
    CupertinoIcons.Filled.CheckmarkShield,
    CupertinoIcons.Filled.CheckmarkSquare,
    CupertinoIcons.Filled.CircleLefthalfed,
    CupertinoIcons.Filled.CircleRighthalfed,
    CupertinoIcons.Filled.Clear,
    CupertinoIcons.Filled.Clipboard,
    CupertinoIcons.Filled.Clock,
    CupertinoIcons.Filled.Cloud,
    CupertinoIcons.Filled.Cone,
    CupertinoIcons.Filled.Cpu,
    CupertinoIcons.Filled.Creditcard,
    CupertinoIcons.Filled.Cross,
    CupertinoIcons.Filled.CrossCircle,
    CupertinoIcons.Filled.CrossVial,
    CupertinoIcons.Filled.Crown,
    CupertinoIcons.Filled.Cube,
    CupertinoIcons.Filled.CupAndSaucer,
    CupertinoIcons.Filled.DeleteLeft,
    CupertinoIcons.Filled.DeleteRight,
    CupertinoIcons.Filled.Dice,
    CupertinoIcons.Filled.Doc,
    CupertinoIcons.Filled.DocBadgeArrowUp,
    CupertinoIcons.Filled.DocBadgePlus,
    CupertinoIcons.Filled.DocOnDoc,
    CupertinoIcons.Filled.DocPlaintext,
    CupertinoIcons.Filled.DocText,
    CupertinoIcons.Filled.Drop,
    CupertinoIcons.Filled.Ear,
    CupertinoIcons.Filled.EllipsisBubble,
    CupertinoIcons.Filled.EllipsisCircle,
    CupertinoIcons.Filled.EllipsisMessage,
    CupertinoIcons.Filled.Envelope,
    CupertinoIcons.Filled.EnvelopeBadge,
    CupertinoIcons.Filled.EnvelopeCircle,
    CupertinoIcons.Filled.EnvelopeOpen,
    CupertinoIcons.Filled.Eraser,
    CupertinoIcons.Filled.ExclamationmarkCircle,
    CupertinoIcons.Filled.ExclamationmarkIcloud,
    CupertinoIcons.Filled.ExclamationmarkSquare,
    CupertinoIcons.Filled.ExclamationmarkTriangle,
    CupertinoIcons.Filled.Externaldrive,
    CupertinoIcons.Filled.Eye,
    CupertinoIcons.Filled.EyeSlash,
    CupertinoIcons.Filled.Facemask,
    CupertinoIcons.Filled.Fanblades,
    CupertinoIcons.Filled.FanbladesSlash,
    CupertinoIcons.Filled.Film,
    CupertinoIcons.Filled.Flag,
    CupertinoIcons.Filled.Flag2Crossed,
    CupertinoIcons.Filled.FlagSlash,
    CupertinoIcons.Filled.Flame,
    CupertinoIcons.Filled.Folder,
    CupertinoIcons.Filled.FolderBadgePlus,
    CupertinoIcons.Filled.Football,
    CupertinoIcons.Filled.ForkKnifeCircle,
    CupertinoIcons.Filled.Forward,
    CupertinoIcons.Filled.ForwardEnd,
    CupertinoIcons.Filled.Fuelpump,
    CupertinoIcons.Filled.Gamecontroller,
    CupertinoIcons.Filled.Gearshape,
    CupertinoIcons.Filled.Gearshape2,
    CupertinoIcons.Filled.Gift,
    CupertinoIcons.Filled.Giftcard,
    CupertinoIcons.Filled.GlobeDesk,
    CupertinoIcons.Filled.Graduationcap,
    CupertinoIcons.Filled.Hammer,
    CupertinoIcons.Filled.HandDraw,
    CupertinoIcons.Filled.HandPointUp,
    CupertinoIcons.Filled.HandPointUpLeft,
    CupertinoIcons.Filled.HandRaised,
    CupertinoIcons.Filled.HandRaisedSlash,
    CupertinoIcons.Filled.HandTap,
    CupertinoIcons.Filled.HandThumbsdown,
    CupertinoIcons.Filled.HandThumbsup,
    CupertinoIcons.Filled.HandWave,
    CupertinoIcons.Filled.HandsSparkles,
    CupertinoIcons.Filled.HeadphonesCircle,
    CupertinoIcons.Filled.Heart,
    CupertinoIcons.Filled.HeartCircle,
    CupertinoIcons.Filled.HeartSlash,
    CupertinoIcons.Filled.HeartTextSquare,
    CupertinoIcons.Filled.Hifispeaker,
    CupertinoIcons.Filled.Homepod,
    CupertinoIcons.Filled.Homepodmini,
    CupertinoIcons.Filled.House,
    CupertinoIcons.Filled.Icloud,
    CupertinoIcons.Filled.IcloudAndArrowDown,
    CupertinoIcons.Filled.IcloudAndArrowUp,
    CupertinoIcons.Filled.InfoBubble,
    CupertinoIcons.Filled.InfoCircle,
    CupertinoIcons.Filled.InfoSquare,
    CupertinoIcons.Filled.Key,
    CupertinoIcons.Filled.KeyIcloud,
    CupertinoIcons.Filled.Keyboard,
    CupertinoIcons.Filled.Lanyardcard,
    CupertinoIcons.Filled.Leaf,
    CupertinoIcons.Filled.Level,
    CupertinoIcons.Filled.Lifepreserver,
    CupertinoIcons.Filled.LightBeaconMax,
    CupertinoIcons.Filled.Lightbulb,
    CupertinoIcons.Filled.LightbulbSlash,
    CupertinoIcons.Filled.LinkCircle,
    CupertinoIcons.Filled.ListBulletCircle,
    CupertinoIcons.Filled.ListBulletClipboard,
    CupertinoIcons.Filled.ListClipboard,
    CupertinoIcons.Filled.Location,
    CupertinoIcons.Filled.Lock,
    CupertinoIcons.Filled.LockCircle,
    CupertinoIcons.Filled.LockOpen,
    CupertinoIcons.Filled.LockSlash,
    CupertinoIcons.Filled.Magazine,
    CupertinoIcons.Filled.Mail,
    CupertinoIcons.Filled.MailStack,
    CupertinoIcons.Filled.Map,
    CupertinoIcons.Filled.Medal,
    CupertinoIcons.Filled.Megaphone,
    CupertinoIcons.Filled.Menucard,
    CupertinoIcons.Filled.Message,
    CupertinoIcons.Filled.MessageBadgeed,
    CupertinoIcons.Filled.Mic,
    CupertinoIcons.Filled.MicSlash,
    CupertinoIcons.Filled.MinusCircle,
    CupertinoIcons.Filled.Moon,
    CupertinoIcons.Filled.MoonStars,
    CupertinoIcons.Filled.Mount,
    CupertinoIcons.Filled.Newspaper,
    CupertinoIcons.Filled.Opticaldisc,
    CupertinoIcons.Filled.Paintbrush,
    CupertinoIcons.Filled.PaintbrushPointed,
    CupertinoIcons.Filled.Paintpalette,
    CupertinoIcons.Filled.PaperclipCircle,
    CupertinoIcons.Filled.Paperplane,
    CupertinoIcons.Filled.PartyPopper,
    CupertinoIcons.Filled.Pause,
    CupertinoIcons.Filled.PauseCircle,
    CupertinoIcons.Filled.Pawprint,
    CupertinoIcons.Filled.PencilCircle,
    CupertinoIcons.Filled.Person,
    CupertinoIcons.Filled.Person2,
    CupertinoIcons.Filled.PersonCircle,
    CupertinoIcons.Filled.PersonCropCircle,
    CupertinoIcons.Filled.PersonCropCircleBadgeMinus,
    CupertinoIcons.Filled.PersonCropCircleBadgePlus,
    CupertinoIcons.Filled.PersonCropSquare,
    CupertinoIcons.Filled.PersonIcloud,
    CupertinoIcons.Filled.PersonTextRectangle,
    CupertinoIcons.Filled.PersonViewfinder,
    CupertinoIcons.Filled.PersonWave2,
    CupertinoIcons.Filled.Phone,
    CupertinoIcons.Filled.PhoneAndWaveform,
    CupertinoIcons.Filled.PhoneArrowDownLeft,
    CupertinoIcons.Filled.PhoneArrowUpRight,
    CupertinoIcons.Filled.PhoneBadgePlus,
    CupertinoIcons.Filled.PhoneCircle,
    CupertinoIcons.Filled.PhoneConnection,
    CupertinoIcons.Filled.Photo,
    CupertinoIcons.Filled.PhotoStack,
    CupertinoIcons.Filled.Pill,
    CupertinoIcons.Filled.Pin,
    CupertinoIcons.Filled.PinCircle,
    CupertinoIcons.Filled.PinSlash,
    CupertinoIcons.Filled.Pip,
    CupertinoIcons.Filled.Play,
    CupertinoIcons.Filled.PlayCircle,
    CupertinoIcons.Filled.PlusApp,
    CupertinoIcons.Filled.PlusBubble,
    CupertinoIcons.Filled.PlusCircle,
    CupertinoIcons.Filled.PlusMessage,
    CupertinoIcons.Filled.PlusSquare,
    CupertinoIcons.Filled.Popcorn,
    CupertinoIcons.Filled.PowerCircle,
    CupertinoIcons.Filled.Printer,
    CupertinoIcons.Filled.Puzzlepiece,
    CupertinoIcons.Filled.PuzzlepieceExtension,
    CupertinoIcons.Filled.QuestionmarkApp,
    CupertinoIcons.Filled.QuestionmarkCircle,
    CupertinoIcons.Filled.QuestionmarkFolder,
    CupertinoIcons.Filled.QuestionmarkSquare,
    CupertinoIcons.Filled.RecordCircle,
    CupertinoIcons.Filled.RectanglePortraitAndArrowForward,
    CupertinoIcons.Filled.RectangleStack,
    CupertinoIcons.Filled.RotateLeft,
    CupertinoIcons.Filled.RotateRight,
    CupertinoIcons.Filled.Ruler,
    CupertinoIcons.Filled.Safari,
    CupertinoIcons.Filled.Scalemass,
    CupertinoIcons.Filled.Scroll,
    CupertinoIcons.Filled.ShazamLogo,
    CupertinoIcons.Filled.Shield,
    CupertinoIcons.Filled.ShieldLefthalfed,
    CupertinoIcons.Filled.ShieldRighthalfed,
    CupertinoIcons.Filled.ShieldSlash,
    CupertinoIcons.Filled.Shippingbox,
    CupertinoIcons.Filled.Shoeprints,
    CupertinoIcons.Filled.Simcard,
    CupertinoIcons.Filled.SmallcircleedCircle,
    CupertinoIcons.Filled.Speaker,
    CupertinoIcons.Filled.SpeakerMinus,
    CupertinoIcons.Filled.SpeakerPlus,
    CupertinoIcons.Filled.SpeakerSlash,
    CupertinoIcons.Filled.SpeakerWave2,
    CupertinoIcons.Filled.SquareAndArrowUp,
    CupertinoIcons.Filled.SquareBottomthirdInseted,
    CupertinoIcons.Filled.SquareOnSquare,
    CupertinoIcons.Filled.SquareSplit1x2,
    CupertinoIcons.Filled.SquareSplit2x1,
    CupertinoIcons.Filled.SquareStack,
    CupertinoIcons.Filled.SquareStack3dUp,
    CupertinoIcons.Filled.SquareTopthirdInseted,
    CupertinoIcons.Filled.Star,
    CupertinoIcons.Filled.StarLeadinghalfed,
    CupertinoIcons.Filled.StarSlash,
    CupertinoIcons.Filled.Staroflife,
    CupertinoIcons.Filled.Stop,
    CupertinoIcons.Filled.StopCircle,
    CupertinoIcons.Filled.Suitcase,
    CupertinoIcons.Filled.SunMax,
    CupertinoIcons.Filled.Tag,
    CupertinoIcons.Filled.Terminal,
    CupertinoIcons.Filled.TextBubble,
    CupertinoIcons.Filled.Theatermasks,
    CupertinoIcons.Filled.Trash,
    CupertinoIcons.Filled.TrashSlash,
    CupertinoIcons.Filled.TrayAndArrowDown,
    CupertinoIcons.Filled.TrayAndArrowUp,
    CupertinoIcons.Filled.Trophy,
    CupertinoIcons.Filled.Tshirt,
    CupertinoIcons.Filled.Tv,
    CupertinoIcons.Filled.TvAndHifispeaker,
    CupertinoIcons.Filled.Umbrella,
    CupertinoIcons.Filled.Video,
    CupertinoIcons.Filled.VideoCircle,
    CupertinoIcons.Filled.VideoSlash,
    CupertinoIcons.Filled.Volleyball,
    CupertinoIcons.Filled.WalletPass,
    CupertinoIcons.Filled.WebCamera,
    CupertinoIcons.Filled.WifiRouter,
    CupertinoIcons.Filled.Wineglass,
    CupertinoIcons.Filled.XmarkApp,
    CupertinoIcons.Filled.XmarkBin,
    CupertinoIcons.Filled.XmarkCircle,
    CupertinoIcons.Filled.XmarkIcloud,
    CupertinoIcons.Filled.XmarkSeal,
    CupertinoIcons.Filled.XmarkShield,
    CupertinoIcons.Filled._4kTv,
)